/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import tools.Util;

/**
 *
 * @author danie
 */
public class JDlg_Vendedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlg_Vendedor
     */
    public JDlg_Vendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedor");
        setLocationRelativeTo(null);  
        Util.habilitar(false, jTxt_Codigo, jTxt_Email, jTxt_Endereco,
                jTxt_Nome, jFmt_CEP, jFmt_CPF, jFmt_Telefone,
                jBtn_Confirmar, jBtn_Cancelar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_Alterar = new javax.swing.JButton();
        jBtn_Excluir = new javax.swing.JButton();
        jBtn_Confirmar = new javax.swing.JButton();
        jBtn_Cancelar = new javax.swing.JButton();
        jBtn_Pesquisar = new javax.swing.JButton();
        jBtn_Incluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxt_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxt_Nome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFmt_CEP = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFmt_CPF = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmt_Telefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxt_Email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxt_Endereco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtn_Alterar.setText("Alterar");
        jBtn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AlterarActionPerformed(evt);
            }
        });

        jBtn_Excluir.setText("Excluir");
        jBtn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ExcluirActionPerformed(evt);
            }
        });

        jBtn_Confirmar.setText("Confirmar");
        jBtn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ConfirmarActionPerformed(evt);
            }
        });

        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jBtn_Pesquisar.setText("Pesquisar");
        jBtn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PesquisarActionPerformed(evt);
            }
        });

        jBtn_Incluir.setText("Incluir");
        jBtn_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_IncluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel7.setText("CEP");

        try {
            jFmt_CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("CPF");

        try {
            jFmt_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmt_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmt_CPFActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone");

        try {
            jFmt_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("E-mail");

        jLabel6.setText("Endereço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxt_Codigo)
                    .addComponent(jTxt_Nome)
                    .addComponent(jTxt_Endereco)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtn_Incluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_Pesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmt_Telefone)
                            .addComponent(jFmt_CPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmt_CEP)
                            .addComponent(jTxt_Email)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(199, 199, 199)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jFmt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTxt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Incluir)
                    .addComponent(jBtn_Alterar)
                    .addComponent(jBtn_Excluir)
                    .addComponent(jBtn_Confirmar)
                    .addComponent(jBtn_Cancelar)
                    .addComponent(jBtn_Pesquisar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AlterarActionPerformed
        Util.habilitar(true, jTxt_Codigo, jTxt_Email, jTxt_Endereco,
        jTxt_Nome, jFmt_CEP, jFmt_CPF, jFmt_Telefone,
        jBtn_Confirmar, jBtn_Cancelar);
        
        Util.habilitar(false, jBtn_Incluir, jBtn_Alterar, jBtn_Excluir, jBtn_Pesquisar, jTxt_Codigo);
        
        jTxt_Nome.grabFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_AlterarActionPerformed

    private void jBtn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja realmente excluir o registro?")){
            Util.limpar(jTxt_Codigo, jTxt_Email, jTxt_Endereco, jTxt_Nome, jFmt_CEP, jFmt_CPF, jFmt_Telefone);
            Util.mensagem("Registro excluído com sucesso!");
        } else {
            Util.mensagem("Exclusão cancelada.");
        }
    }//GEN-LAST:event_jBtn_ExcluirActionPerformed

    private void jBtn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ConfirmarActionPerformed
        Util.habilitar(false, jTxt_Codigo, jTxt_Email, jTxt_Endereco,
        jTxt_Nome, jFmt_CEP, jFmt_CPF, jFmt_Telefone,
        jBtn_Confirmar, jBtn_Cancelar);
        
        Util.habilitar(true, jBtn_Incluir, jBtn_Alterar, jBtn_Excluir, jBtn_Pesquisar);
        
        Util.limpar(jTxt_Codigo, jTxt_Email, jTxt_Endereco, jTxt_Nome, jFmt_CEP, jFmt_CPF, jFmt_Telefone);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_ConfirmarActionPerformed

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        Util.habilitar(false, jTxt_Codigo, jTxt_Email, jTxt_Endereco,
        jTxt_Nome, jFmt_CEP, jFmt_CPF, jFmt_Telefone,
        jBtn_Confirmar, jBtn_Cancelar);
        
        Util.habilitar(true, jBtn_Incluir, jBtn_Alterar, jBtn_Excluir, jBtn_Pesquisar);
        Util.limpar(jTxt_Codigo, jTxt_Email, jTxt_Endereco, jTxt_Nome, jFmt_CEP, jFmt_CPF, jFmt_Telefone);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_CancelarActionPerformed

    private void jBtn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PesquisarActionPerformed
        // TODO add your handling code here:
        Util.mensagem("Não Implementado");
    }//GEN-LAST:event_jBtn_PesquisarActionPerformed

    private void jBtn_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_IncluirActionPerformed
        Util.habilitar(true, jTxt_Codigo, jTxt_Email, jTxt_Endereco,
        jTxt_Nome, jFmt_CEP, jFmt_CPF, jFmt_Telefone,
        jBtn_Confirmar, jBtn_Cancelar);

        Util.habilitar(false, jBtn_Incluir, jBtn_Alterar, jBtn_Excluir, jBtn_Pesquisar);

        Util.limpar(jTxt_Codigo, jTxt_Email, jTxt_Endereco, jTxt_Nome, jFmt_CEP, jFmt_CPF, jFmt_Telefone);
        
        jTxt_Codigo.grabFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_IncluirActionPerformed

    private void jFmt_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmt_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmt_CPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_Vendedor dialog = new JDlg_Vendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Alterar;
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Confirmar;
    private javax.swing.JButton jBtn_Excluir;
    private javax.swing.JButton jBtn_Incluir;
    private javax.swing.JButton jBtn_Pesquisar;
    private javax.swing.JFormattedTextField jFmt_CEP;
    private javax.swing.JFormattedTextField jFmt_CPF;
    private javax.swing.JFormattedTextField jFmt_Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTxt_Codigo;
    private javax.swing.JTextField jTxt_Email;
    private javax.swing.JTextField jTxt_Endereco;
    private javax.swing.JTextField jTxt_Nome;
    // End of variables declaration//GEN-END:variables
}
