/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author danie
 */
public class JFrm_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JFrm_Principal
     */
    public JFrm_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Sistema de compras de flores artificiais");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnb_Cadastros = new javax.swing.JMenu();
        jMni_Usuarios = new javax.swing.JMenuItem();
        jMni_Vendedor = new javax.swing.JMenuItem();
        jMni_Fornecedor = new javax.swing.JMenuItem();
        jMni_Produtos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMni_Sair = new javax.swing.JMenuItem();
        jMnb_Movimentos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnb_Cadastros.setText("Cadastros");

        jMni_Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Usuarios.setText("Usuário");
        jMni_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_UsuariosActionPerformed(evt);
            }
        });
        jMnb_Cadastros.add(jMni_Usuarios);

        jMni_Vendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Vendedor.setText("Vendedor");
        jMni_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_VendedorActionPerformed(evt);
            }
        });
        jMnb_Cadastros.add(jMni_Vendedor);

        jMni_Fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Fornecedor.setText("Fornecedor");
        jMni_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_FornecedorActionPerformed(evt);
            }
        });
        jMnb_Cadastros.add(jMni_Fornecedor);

        jMni_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMni_Produtos.setText("Produtos");
        jMni_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_ProdutosActionPerformed(evt);
            }
        });
        jMnb_Cadastros.add(jMni_Produtos);
        jMnb_Cadastros.add(jSeparator1);

        jMni_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMni_Sair.setText("Sair");
        jMni_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMni_SairActionPerformed(evt);
            }
        });
        jMnb_Cadastros.add(jMni_Sair);

        jMenuBar1.add(jMnb_Cadastros);

        jMnb_Movimentos.setText("Movimentos");
        jMenuBar1.add(jMnb_Movimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMni_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_UsuariosActionPerformed
        // TODO add your handling code here:
        JDlg_Usuarios jDlgUsuarios = new JDlg_Usuarios(null, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMni_UsuariosActionPerformed

    private void jMni_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_VendedorActionPerformed
        // TODO add your handling code here:
        JDlg_Vendedor jDlg_Vendedor = new JDlg_Vendedor(null, true);
        jDlg_Vendedor.setVisible(true);
    }//GEN-LAST:event_jMni_VendedorActionPerformed

    private void jMni_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMni_SairActionPerformed

    private void jMni_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_FornecedorActionPerformed
        // TODO add your handling code here:
        JDlg_Clientes jDlg_Fornecedor = new JDlg_Clientes(null, true);
        jDlg_Fornecedor.setVisible(true);
    }//GEN-LAST:event_jMni_FornecedorActionPerformed

    private void jMni_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMni_ProdutosActionPerformed
        // TODO add your handling code here:
        JDlg_Produtos jDlg_Produtos = new JDlg_Produtos(null, true);
        jDlg_Produtos.setVisible(true);
    }//GEN-LAST:event_jMni_ProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrm_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnb_Cadastros;
    private javax.swing.JMenu jMnb_Movimentos;
    private javax.swing.JMenuItem jMni_Fornecedor;
    private javax.swing.JMenuItem jMni_Produtos;
    private javax.swing.JMenuItem jMni_Sair;
    private javax.swing.JMenuItem jMni_Usuarios;
    private javax.swing.JMenuItem jMni_Vendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
